bcancer/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [  
    
    
    url(r'^', include('gui.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gui/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UserHome
from . import views

app_name='gui'
urlpatterns =[
	
	
	url(r'^input/$',UserHome.as_view(), name='input'),
	url(r'^train/$', views.model_form_train ,name='train'),
	url(r'^$', auth_views.login, {'template_name': 'admin-home.html'}, name='admin_home'),
	url(r'^graph/$', views.get_image ,name='graph'),
	url(r'^gra/$', auth_views.login, {'template_name': 'graph.html'}, name='gra'),
	
		
]

gui/models.py
from django.db import models

# Create your models here.
class parameter(models.Model):
	radius_mean=models.FloatField()
	texture_mean=models.FloatField()
	perimeter_mean=models.FloatField()
	area_mean=models.FloatField()
	smoothness_mean=models.FloatField()
	compactness_mean=models.FloatField()
	concavity_mean=models.FloatField()
	concave_points_mean=models.FloatField()
	symmetry_mean=models.FloatField()
	fractal_dimension_mean=models.FloatField()
	radius_se=models.FloatField()
	texture_se=models.FloatField()
	perimeter_se=models.FloatField()
	area_se=models.FloatField()
	smoothness_se=models.FloatField()
	compactness_se=models.FloatField()
	concavity_se=models.FloatField()
	concave_points_se=models.FloatField()
	symmetry_se=models.FloatField()
	fractal_dimension_se=models.FloatField()
	radius_worst=models.FloatField()
	texture_worst=models.FloatField()
	perimeter_worst=models.FloatField()
	area_worst=models.FloatField()
	smoothness_worst=models.FloatField()
	compactness_worst=models.FloatField()
	concavity_worst=models.FloatField()
	concave_points_worst=models.FloatField()
	symmetry_worst=models.FloatField()
	fractal_dimension_worst=models.FloatField()

class Document(models.Model):
	document=models.FileField(upload_to='documents/')

gui/views.py
# importing required modules
import os
import csv
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth.views import login
from django.conf import settings
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import pickle
import io
import csv
import ast
from .userform import DataForm,DocumentForm
from .p2 import mlp,mlp_csv
from django.views.generic import View
from .models import parameter
from django.template.loader import get_template
from .graph import graph
f1=io.BytesIO()

class UserHome(TemplateView):
	template_name = 'input.html'

	def get(self, request):
		form1=DataForm()
		return render(request, self.template_name, {'form1' : form1})

	def post(self, request):
		form1 = DataForm(request.POST)
		if form1.is_valid():
			form1.save()
			radius_mean=form1.cleaned_data['radius_mean']
			texture_mean=form1.cleaned_data['texture_mean']
			perimeter_mean=form1.cleaned_data['perimeter_mean']
			area_mean=form1.cleaned_data['area_mean']
			smoothness_mean=form1.cleaned_data['smoothness_mean']
			compactness_mean=form1.cleaned_data['compactness_mean']
			concavity_mean=form1.cleaned_data['concavity_mean']
			concave_points_mean=form1.cleaned_data['concave_points_mean']
			symmetry_mean=form1.cleaned_data['symmetry_mean']
			fractal_dimension_mean=form1.cleaned_data['fractal_dimension_mean']
			radius_se=form1.cleaned_data['radius_se']
			texture_se=form1.cleaned_data['texture_se']
			perimeter_se=form1.cleaned_data['perimeter_se']
			area_se=form1.cleaned_data['area_se']
			smoothness_se=form1.cleaned_data['smoothness_se']
			compactness_se=form1.cleaned_data['compactness_se']
			concavity_se=form1.cleaned_data['concavity_se']
			concave_points_se=form1.cleaned_data['concave_points_se']
			symmetry_se=form1.cleaned_data['symmetry_se']
			fractal_dimension_se=form1.cleaned_data['fractal_dimension_se']
			radius_worst=form1.cleaned_data['radius_worst']
			texture_worst=form1.cleaned_data['texture_worst']
			perimeter_worst=form1.cleaned_data['perimeter_worst']
			area_worst=form1.cleaned_data['area_worst']
			smoothness_worst=form1.cleaned_data['smoothness_worst']
			compactness_worst=form1.cleaned_data['compactness_worst']
			concavity_worst=form1.cleaned_data['concavity_worst']
			concave_points_worst=form1.cleaned_data['concave_points_worst']
			symmetry_worst=form1.cleaned_data['symmetry_worst']
			fractal_dimension_worst=form1.cleaned_data['fractal_dimension_worst']	
			
			pred = mlp(radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave_points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst)
			args = {'form1' : form1, 'pred' : pred}
			form1=DataForm()
			
		return render(request,self.template_name,args)		

#for training:
def model_form_train(request):
	if request.method == 'POST':
		form2=DocumentForm(request.POST, request.FILES)
		if form2.is_valid():
			form2.save()
			csv_file=request.FILES['document']
			if not csv_file.name.endswith('.csv'):
				messages.error(request,'File is not csv type')
				return render(request, "training.html" ,{'form2' : form2})
			file=csv_file.name
			
			accuracy = mlp_csv(file)
			accuracy = accuracy*100
			return render(request, "training.html" ,{'form2' : form2, 'accuracy' : accuracy})
	else:
		form2=DocumentForm(request.POST, request.FILES)
		return render(request, "training.html" ,{'form2' : form2})

def get_image_rfc(request):
	f=open('finalized_model_mlp.sav', 'rb')
	cl_mlp=pickle.load(f)
	accuracy_mlp=pickle.load(f)
	a=pickle.load(f)

	labels = 'Right Prediction', 'Wrong Prediction'
	plt.rcParams['font.size'] = 7.0
	sizes = [a[0][0],a[0][1]]
	colors = ['blue', 'red']
	explode = (0, 0)  # explode 1st slice
	ax=plt.subplot(131)
	ax.set_title('MLP:          Good Fistulae')
	ttl=ax.title
	ttl.set_position([.2,0.9])
	plt.axis('equal')
	plt.rcParams['font.size'] = 5.0
	plt.pie(sizes, explode=explode, labels=labels, colors=colors,
	        autopct='%1.0f%%', shadow=False, startangle=150)

	labels = 'Right Prediction', 'Wrong Prediction'
	plt.rcParams['font.size'] = 7.0
	sizes = [a[1][1],a[1][0]]
	colors = ['blue', 'red']
	explode = (0, 0)  # explode 1st slice
	ax=plt.subplot(132)
	ax.set_title('Bad Fistulae')
	ttl=ax.title
	ttl.set_position([.4,0.9])
	plt.axis('equal')
	plt.rcParams['font.size'] = 5.0
	plt.pie(sizes, explode=explode, labels=labels, colors=colors,
	        autopct='%1.0f%%', shadow=False, startangle=180)

	labels = 'Accuracy', ''
	plt.rcParams['font.size'] = 7.0
	sizes = [accuracy_mlp,1-accuracy_mlp]
	colors = ['blue', 'red']
	explode = (0, 0)  # explode 1st slice
	ax=plt.subplot(133)
	plt.axis('equal')
	plt.pie(sizes, explode=explode, labels=labels, colors=colors,
	        autopct='%1.0f%%', shadow=False, startangle=150)
	plt.savefig(f1, format='png')
	
    	#plt.show()
	return HttpResponse(f1.getvalue(), content_type='image/png')
    
def get_image(request):
	r=graph('finalized_model_mlp.sav')
	return r    
    
    

gui/templates/admin-base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}" />
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}Breast Cancer Prediction{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
    
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-color="green" data-image="{% static 'assets/img/sidebar-1.png' %}">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="logo">
                <a href="#" class="simple-text">
                    &nbsp&nbsp&nbsp&nbsp<img class="mb-4" src="{% static 'img/bc.jpg' %}" alt="" width="150" height="130">
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="active">
                        <a href="{% url 'gui:admin_home' %}" style="background:#ff0080">
                            <i class="material-icons">dashboard</i>
                            <p>Analysis</p>
                        </a>
                    </li>
                    
                     <li>
                        <a href="{% url 'gui:input' %}">
                            <i class="material-icons"><!-- graphs --></i>
                            <p>Prediction</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'gui:train' %}">
                            <i class="material-icons"><!-- history --></i>
                            <p>Train your Data</p>
                        </a>
                    </li>
                </ul>
            </div>
            
        </div>
        
        
        <div class="main-panel">                
            <div class="content">
        <main>
            {% block content %}
            
            {% endblock %}
          </main>
          </div>
        </div>
        </div>
        
        
    </div>
    
</body>

<!--   Core JS Files   -->
<script src="{% static 'assets/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/material.min.js' %}" type="text/javascript"></script>
<!--  Charts Plugin -->
<script src="{% static 'assets/js/chartist.min.js' %}"></script>
<!--  Dynamic Elements plugin -->
<script src="{% static 'assets/js/arrive.min.js' %}"></script>
<!--  PerfectScrollbar Library -->
<script src="{% static 'assets/js/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'assets/js/material-dashboard.js' %}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/js/demo.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

    });
</script>

</html>

gui/templates/admin-home.html
{% extends 'admin-base.html' %}

{% block content %}           
<div class="row">
    <div class="col-md-4" style="width:100%;">          
        <div class="card">                                                 
            <img id="img" src="{% url 'gui:graph' %}" style="width:100%"; height="30px";>        
        </div>
    </div>
</div>
{% endblock %}
 

gui/templates/graph.html
{% extends 'admin-base.html' %}

{% block content %}           
<h3><b>Pictorial representations: </b></h3><br>
<html>
<div class="row" style="width:100%; padding: 0px; margin: 0px;">
    <div class="col-md-4" style="width:100%; padding: 0px 0px 0px 0px; margin: 0px;">
        <div class="card" style="padding: 0px 0px 0px 0px; margin: 0px; box-sizing: content-box; display:block;">                                                 
            <img id="img" src="{% url 'gui:graph' %}" style="padding: 0px 0px 0px 0px; margin: 0px; display:block; border:0; box-sizing: content-box; height: 800px">
        </div>
    </div>
                <!-- <div class="row"> -->
</div>
{% endblock %}

gui/templates/input.html
{% extends 'admin-base.html' %}

{% load crispy_forms_tags %}
{% load static %}
{% block title %}Prediction{% endblock %}
{% block disclaimer %}
{% endblock %}
{% block content %}


<doctype html>
<html lang="en">
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
<head>
<style type="text/css">

  .accordion {
    background-color: #ff0080;
    color: white;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    text-align: left;
    border: none;
    outline: none;
    transition: 0.4s;
}
/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active1, .accordion:hover {
    background-color: #ffb3d9;
}
/* Style the accordion panel. Note: hidden by default */
.accordion:after {
    content: '\02795'; /* Unicode character for "plus" sign (+) */
    font-size: 13px;
    color: white;
    float: right;
    margin-left: 5px;
}
.active1:after {
    content: "\2796"; /* Unicode character for "minus" sign (-) */
    }
.panel {
    padding: 0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;

}
.result {
    background-color: #ff0080;
    color: white;
    cursor: pointer;
    padding: 18px;
    border: none;
    outline: none;
    transition: 0.4s;
}
</style>
 </head>




        <div class="container ">
          <h2 style="text-align:center;">Prediction for Breast Cancer</h2><br><br>
          <div class="row">
        <div class="col-sm-4">
      
          <form method="post">
            {% csrf_token %}

           <!-- # {{ form1 | crispy }} -->
           {% csrf_token %}

           <!-- start -->
         
          

           </div>
           </div>

<div class="row">
        <div class="col-sm-11">
<button class="accordion">Means*</button>
<div class="panel">
  <div class="row">
        <div class="col-sm-5">
            
  {{ form1.radius_mean | as_crispy_field }}
  {{ form1.texture_mean | as_crispy_field }}
  {{ form1.perimeter_mean | as_crispy_field }}
  {{ form1.area_mean | as_crispy_field }}
  {{ form1.smoothness_mean | as_crispy_field }} 
  {{ form1.compactness_mean | as_crispy_field }} 
  {{ form1.concavity_mean | as_crispy_field }} 
  {{ form1.concave_points_mean | as_crispy_field }} 
  {{ form1.symmetry_mean | as_crispy_field }} 
  {{ form1.fractal_dimension_mean | as_crispy_field }}  
  </div>
  </div>     
</div>
<button class="accordion">Standard Errors*</button>
<div class="panel">
<div class="row">
        <div class="col-sm-5">
            {{ form1.radius_se | as_crispy_field }}
            {{ form1.texture_se | as_crispy_field }}
            {{ form1.perimeter_se | as_crispy_field }}
            {{ form1.area_se | as_crispy_field }}
            {{ form1.smoothness_se | as_crispy_field }} 
            {{ form1.compactness_se | as_crispy_field }} 
            {{ form1.concavity_se | as_crispy_field }} 
            {{ form1.concave_points_se | as_crispy_field }} 
            {{ form1.symmetry_se | as_crispy_field }} 
            {{ form1.fractal_dimension_se | as_crispy_field }} 
  </div>
  </div>                  
</div>
<button class="accordion">Worsts*</button>
<div class="panel">
<div class="row">
        <div class="col-sm-5">
            {{ form1.radius_worst | as_crispy_field }}
            {{ form1.texture_worst | as_crispy_field }}
            {{ form1.perimeter_worst | as_crispy_field }}
            {{ form1.area_worst | as_crispy_field }}
            {{ form1.smoothness_worst | as_crispy_field }} 
            {{ form1.compactness_worst | as_crispy_field }} 
            {{ form1.concavity_worst | as_crispy_field }} 
            {{ form1.concave_points_worst | as_crispy_field }} 
            {{ form1.symmetry_worst | as_crispy_field }} 
            {{ form1.fractal_dimension_worst | as_crispy_field }}
  </div>
  </div>       
</div>



            
          
          </div>
          </div>
        </div>
        
        <div class="container">
        
        
        <h4> Results : {{ pred }} </h4>
      
            <button type="submit" class="result">Result</button>
            
        </form>
          
    
        </div>

<!-- * -->

  <script>
var acc = document.getElementsByClassName("accordion");
var i;
for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active1");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

{% endblock %}
</html>

gui/templates/training.html
{% extends 'admin-base.html' %}
{% block title %}Upload{% endblock %}
{% load crispy_forms_tags %}
{% block disclaimer %}
{% endblock %}
{% block content %}

<style type="text/css">
.result {
    background-color: #ff0080;
    color: white;
    cursor: pointer;
    padding: 8px;
    border: none;
    outline: none;
    transition: 0.4s;
}
</style>
<doctype html>
<html lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    
        <h2 align="center"> Training and testing </h2><br><br>
        <div class="container " style="margin:auto; width:40%; border: 3px solid #ff0080"  >
        <div class="row" style="margin:auto; width:50%;">
        <div class="col-sm-5" style="margin:auto; width:100%;">
            <form method="post" enctype="multipart/form-data" action="#">
                {% csrf_token %}
                <br>
                {{ form2.document }}
          
                <br><br><button type="submit" class="result">Train and test</button>
                <!-- <button type="submit" class="result"></button> -->
                <br><br>
        
                <h4>Accuracy:{{ accuracy }}</h4>
                <!-- {{ pred1 }} -->
                <br>
                <br>
              </form>

          </div>
          </div>
        </div>
      
    

{% endblock %}